<?php
    // Lista de comunas obtenida de la página
    $comunas = array(
        'Algarrobo',
        'Alhué',
        'Alto Biobío',
        'Alto del Carmen',
        'Alto Hospicio',
        'Ancud',
        'Andacollo',
        'Angol',
        'Antártica',
        'Antofagasta',
        'Antuco',
        'Arauco',
        'Arica',
        'Aysén',
        'Buin',
        'Bulnes',
        'Cabildo',
        'Cabo de Hornos',
        'Cabrero',
        'Calama',
        'Calbuco',
        'Caldera',
        'Calera de Tango',
        'Calle Larga',
        'Camarones',
        'Camiña',
        'Canela',
        'Cañete',
        'Carahue',
        'Cartagena',
        'Casablanca',
        'Castro',
        'Catemu',
        'Cauquenes',
        'Cerrillos',
        'Cerro Navia',
        'Chaitén',
        'Chañaral',
        'Chanco',
        'Chépica',
        'Chiguayante',
        'Chile Chico',
        'Chillán',
        'Chillán Viejo',
        'Chimbarongo',
        'Cholchol',
        'Chonchi',
        'Cisnes',
        'Cobquecura',
        'Cochamó',
        'Cochrane',
        'Codegua',
        'Coelemu',
        'Coihueco',
        'Coinco',
        'Colbún',
        'Colchane',
        'Colina',
        'Collipulli',
        'Coltauco',
        'Combarbalá',
        'Concepción',
        'Conchalí',
        'Concón',
        'Constitución',
        'Contulmo',
        'Copiapó',
        'Coquimbo',
        'Coronel',
        'Corral',
        'Coyhaique',
        'Cunco',
        'Curacautín',
        'Curacaví',
        'Curaco de Vélez',
        'Curanilahue',
        'Curarrehue',
        'Curepto',
        'Curicó',
        'Dalcahue',
        'Diego de Almagro',
        'Doñihue',
        'El Bosque',
        'El Carmen',
        'El Monte',
        'El Quisco',
        'El Tabo',
        'Empedrado',
        'Ercilla',
        'Estación Central',
        'Florida',
        'Freire',
        'Freirina',
        'Fresia',
        'Frutillar',
        'Futaleufú',
        'Futrono',
        'Galvarino',
        'General Lagos',
        'Gorbea',
        'Graneros',
        'Guaitecas',
        'Hijuelas',
        'Hualaihué',
        'Hualañé',
        'Hualpén',
        'Hualqui',
        'Huara',
        'Huasco',
        'Huechuraba',
        'Illapel',
        'Independencia',
        'Iquique',
        'Isla de Maipo',
        'Isla de Pascua',
        'Juan Fernández',
        'La Calera',
        'La Cisterna',
        'La Cruz',
        'La Estrella',
        'La Florida',
        'Lago Ranco',
        'Lago Verde',
        'La Granja',
        'Laguna Blanca',
        'La Higuera',
        'Laja',
        'La Ligua',
        'Lampa',
        'Lanco',
        'La Pintana',
        'La Reina',
        'Las Cabras',
        'Las Condes',
        'La Serena',
        'La Unión',
        'Lautaro',
        'Lebu',
        'Licantén',
        'Limache',
        'Linares',
        'Litueche',
        'Llaillay',
        'Llanquihue',
        'Lo Barnechea',
        'Lo Espejo',
        'Lolol',
        'Loncoche',
        'Longaví',
        'Lonquimay',
        'Lo Prado',
        'Los Álamos',
        'Los Andes',
        'Los Ángeles',                                                                                
        'Los Lagos',
        'Los Muermos',
        'Los Sauces',
        'Los Vilos',
        'Lota',
        'Lumaco',
        'Machalí',
        'Macul',
        'Máfil',
        'Maipú',
        'Malloa',
        'Marchihue',
        'María Elena',
        'María Pinto',
        'Mariquina',
        'Maule',
        'Maullín',
        'Mejillones',
        'Melipeuco',
        'Melipilla',
        'Molina',
        'Monte Patria',
        'Mostazal',
        'Mulchén',
        'Nacimiento',
        'Nancagua',
        'Natales',
        'Navidad',
        'Negrete',
        'Ninhue',
        'Nogales',
        'Nueva Imperial',
        'Ñiquén',
        'Ñuñoa',
        'O Higgins',
        'Olivar',
        'Ollagüe',
        'Olmué',
        'Osorno',
        'Ovalle',
        'Padre Hurtado',
        'Padre Las Casas',
        'Paihuano',
        'Paillaco'                              
        ); 
   ?>